"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, FolderGit2, Plus, Search, Sparkles, X } from "lucide-react";

type Project = { id: string; name: string; description: string; repository?: string | null; status: string; updated_at: string };

export function ProjectsManager(){
  const[projects,setProjects]=useState<Project[]>([]);const[loading,setLoading]=useState(true);const[showCreate,setShowCreate]=useState(false);const[error,setError]=useState("");const[upgradeUrl,setUpgradeUrl]=useState("");const[query,setQuery]=useState("");
  useEffect(()=>{let active=true;fetch("/api/projects").then(async response=>({response,data:await response.json() as {projects?:Project[];error?:string}})).then(({response,data})=>{if(!active)return;if(response.ok)setProjects(data.projects??[]);else setError(data.error??"Could not load projects.");setLoading(false)}).catch(()=>{if(active){setError("Could not load projects.");setLoading(false)}});return()=>{active=false}},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setUpgradeUrl("");const form=new FormData(event.currentTarget);const response=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),description:form.get("description")})});const data=await response.json() as {project?:Project;error?:string;code?:string;upgradeUrl?:string};if(response.ok&&data.project){window.location.href=`/project/${data.project.id}`}else{setError(data.error??"Could not create project.");if(data.code==="PROJECT_LIMIT_REACHED")setUpgradeUrl(data.upgradeUrl??"/pricing")}}
  const visibleProjects=projects.filter(project=>`${project.name} ${project.description} ${project.repository??""}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="projects-toolbar"><div><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects" aria-label="Search projects"/></div><button onClick={()=>setShowCreate(true)}><Plus size={13}/> New project</button></div>{error&&<div className="manager-error">{error} {error.includes("Sign in")&&<Link href="/login">Sign in</Link>}{upgradeUrl&&<Link href={upgradeUrl}>Upgrade to Pro</Link>}</div>}{loading?<div className="manager-loading"><i/>Loading your projects...</div>:projects.length===0?<div className="projects-empty"><span><Sparkles size={21}/></span><h2>Create your first KODO project</h2><p>Project files, agent history, versions, and deployments will be saved here.</p><button onClick={()=>setShowCreate(true)}><Plus size={14}/> New project</button></div>:visibleProjects.length===0?<div className="projects-empty"><Search size={21}/><h2>No matching projects</h2><p>Try a different name, repository or description.</p></div>:<div className="project-grid">{visibleProjects.map((project,index)=><Link href={`/project/${project.id}`} className="project-card" key={project.id}><div className={`project-card-cover ${["violet","green","amber","blue"][index%4]}`}><span className="project-glyph"><Sparkles size={17}/></span><div><i/><i/><i/></div></div><section><div><h2>{project.name}</h2><span className={project.status}>{project.status}</span></div><p>{project.description||"KODO project"}</p><footer><span><FolderGit2 size={13}/>{project.repository||"Blank project"}</span><time>{new Date(project.updated_at).toLocaleDateString()}</time></footer></section><ArrowRight className="card-arrow" size={17}/></Link>)}</div>}{showCreate&&<div className="manager-modal"><button className="manager-scrim" onClick={()=>setShowCreate(false)} aria-label="Close"/><form onSubmit={create}><button type="button" className="manager-close" onClick={()=>setShowCreate(false)}><X size={17}/></button><span className="manager-icon"><Sparkles size={19}/></span><h2>New project</h2><p>Start blank now. GitHub can be connected from the project workspace.</p><label>Project name<input name="name" placeholder="My ambitious project" required autoFocus/></label><label>What are you building?<textarea name="description" placeholder="A SaaS dashboard for..."/></label><button className="manager-submit">Create project <ArrowRight size={14}/></button></form></div>}</>
}
