import { ArrowRight, Check, Minus } from "lucide-react";
import { PublicNav } from "../components/public-nav";

const plans = [
  { name: "Free", price: "₹0", desc: "Explore KODO and build your first project.", cta: "Start free", features: ["500 agent credits / month", "2 active projects", "Public repositories", "Preview deployments"] },
  { name: "Pro", price: "₹1,999", desc: "For individual builders shipping real products.", cta: "Start Pro", popular: true, features: ["5,000 agent credits / month", "Unlimited projects", "Private repositories", "Production deployments", "Priority agent queue"] },
  { name: "Team", price: "₹5,999", desc: "For teams building together with shared context.", cta: "Start Team", features: ["15,000 shared credits / month", "Up to 10 members", "Advanced permissions", "Shared automations", "Priority support"] },
];

export default function PricingPage(){return <main className="public-page"><PublicNav /><section className="pricing-hero"><p>PLANS THAT SCALE WITH THE WORK</p><h1>Build more.<br />Stay in control.</h1><span>Start free, then upgrade when KODO becomes part of your daily workflow.</span><div className="billing-toggle"><button className="active">Monthly</button><button>Yearly <em>Save 20%</em></button></div></section><section className="pricing-grid">{plans.map(plan=><article className={plan.popular?"popular":""} key={plan.name}>{plan.popular&&<span className="popular-label">MOST POPULAR</span>}<header><h2>{plan.name}</h2><p>{plan.desc}</p></header><div className="plan-price"><strong>{plan.price}</strong><span>{plan.price!=="₹0"?"/ month":"forever"}</span></div><a href="/signup">{plan.cta}<ArrowRight size={15}/></a><ul>{plan.features.map(feature=><li key={feature}><Check size={14}/>{feature}</li>)}</ul></article>)}</section><section className="plan-compare"><h2>Everything you need to ship</h2><div className="compare-table"><header><span>Feature</span><span>Free</span><span>Pro</span><span>Team</span></header>{[["AI planning and coding",true,true,true],["Preview environments",true,true,true],["Private repositories",false,true,true],["Production deployments",false,true,true],["Team permissions",false,false,true],["Shared agent automations",false,false,true]].map(([name,...values])=><div key={String(name)}><span>{name}</span>{values.map((value,index)=><span key={index}>{value?<Check size={14}/>:<Minus size={14}/>}</span>)}</div>)}</div></section><section className="pricing-faq"><h2>Questions, answered.</h2><div>{[["What is an agent credit?","Credits measure the work KODO performs while planning, editing, and verifying your code. You can always see the estimated cost before a large run."],["Can I change plans anytime?","Yes. Upgrade, downgrade, or cancel from your billing settings. Your projects and code remain yours."],["Does KODO train on my private code?","No. Your private repositories and project context are used only to complete your requests."],["Can my team approve deployments?","Yes. Team plans include role-based controls for pull requests, secrets, and production publishing."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section><footer className="marketing-footer"><span>© 2026 KODO.DIY</span><div><a href="/">Home</a><a href="/docs">Docs</a><a href="mailto:hello@kodo.diy">Contact</a></div><span>Build ambitious software.</span></footer></main>}
