import { ArrowRight, CheckCircle2, GitBranch, GitPullRequest, Plus, ShieldCheck, Sparkles, Terminal, WandSparkles, Zap } from "lucide-react";
import { ProductShell } from "../components/product-shell";

const activity = [
  { title: "Build KODO onboarding flow", repo: "kodo/web", branch: "feat/onboarding", status: "Working", time: "6m" },
  { title: "Fix mobile navigation", repo: "kodo/web", branch: "fix/mobile-nav", status: "Ready for review", time: "14m" },
  { title: "Add rate limits to public routes", repo: "kodo/api", branch: "feat/rate-limits", status: "Working", time: "22m" },
  { title: "Implement usage alerts", repo: "kodo/dashboard", branch: "feat/usage-alerts", status: "Done", time: "Yesterday" },
];

export default function WorkspacePage(){return <ProductShell active="home" title="What should we build?" context="KODO AGENTS" actions={<div className="system-ready"><i /> Systems ready</div>}><p className="workspace-lede">Describe the result. KODO will plan the work and show you every change.</p><form className="workspace-composer" action="/project/new"><textarea name="task" placeholder="Plan, search, build anything" aria-label="Give KODO a task"/><div><button type="button" className="composer-plus"><Plus size={16}/></button><button type="button" className="composer-repo"><GitBranch size={14}/> kodo/web <span>⌄</span></button><span/><button type="button" className="composer-model"><Sparkles size={13}/> Auto</button><button className="composer-submit"><ArrowRight size={16}/></button></div><footer><span>@ context</span><span>/ commands</span><span>⌘ ↵ run</span></footer></form><div className="workspace-actions"><a href="/project/new"><WandSparkles size={16}/><span><b>Build a feature</b><small>Turn a product idea into working code</small></span><ArrowRight size={14}/></a><a href="/project/new"><Zap size={16}/><span><b>Fix an issue</b><small>Debug failures and verify the repair</small></span><ArrowRight size={14}/></a><a href="/agents"><GitPullRequest size={16}/><span><b>Review changes</b><small>Find bugs before they reach production</small></span><ArrowRight size={14}/></a></div><section className="workspace-recent"><header><h2>Recent agents</h2><a href="/agents">View all <ArrowRight size={13}/></a></header><div>{activity.map(item=><a href="/project/kodo-web" key={item.title}><span className={`recent-status ${item.status.toLowerCase().replaceAll(" ","-")}`}>{item.status==="Working"?<i/>:item.status==="Ready for review"?<GitPullRequest size={14}/>:<CheckCircle2 size={14}/>}</span><span><b>{item.title}</b><small><GitBranch size={11}/>{item.repo} · {item.branch}</small></span><em>{item.status}</em><time>{item.time}</time><ArrowRight size={14}/></a>)}</div></section><div className="workspace-info"><article><Terminal size={17}/><div><h3>Continue from anywhere</h3><p>Start in the browser, hand work to the cloud, and pick it up later from desktop or CLI.</p></div></article><article><ShieldCheck size={17}/><div><h3>You approve important actions</h3><p>Production deploys, secrets, and destructive commands always stay visible.</p></div></article></div></ProductShell>}
